### PR TITLE
Basic structure and style for Recipe Details page

### PR DESCRIPTION
**Pull request by juliakimseohyeon**
Hi team, when you have a moment please take a look at the Recipe Details page, thank you!

### CODE REVIEW

**Comment by nicmart-dev** [comment]
sample URL: http://localhost:3000/recipes/1

**Review by nicmart-dev — APPROVED** [review]

**Review by nicmart-dev — CHANGES_REQUESTED** [review]
Looks good! 
Similar feedback I left for your other PR applies:
1. As login and saved recipes will be taken opportunistically, I suggest to hide the login icon behind a feature toggle (or comment out the associated code) and the favorite heart.
2. small enhancement, you used a logout instead of login icon.
3. Add `.DS_Store` to `.gitignore`

**Comment by juliakimseohyeon** [comment]
@nicmart-dev thank you for pointing those out. The logout button has been commented out and .DS_STORE added to gitignore file

**Comment by nicmart-dev** [comment]
> (...) .DS_STORE added to gitignore file

I think you need to remove existing committed files manually after adding them to .gitignore

**Comment by juliakimseohyeon** [comment]
Thanks for pointing that out @nicmart-dev . I've removed all instances of `.DS_Store` by using the command `find . -name .DS_Store -exec rm -f {} \;`

**Review by nicmart-dev — CHANGES_REQUESTED** [review]
Should the two `.json` files file be part of the PR? They sit at the root and don't see them used in the codebase. They seem like test files.

**Comment by juliakimseohyeon** [comment]
@nicmart-dev Unnecessary json files removed!

**Review by nicmart-dev — APPROVED** [review]

**Pull request merged**
